// Generated from TRADE JOURNAL(PROP FIRM) 200K.docx. Re-run the importer when the Word document changes.
window.KINGFX_IMPORTED_TRADES = [
    {
        "import_id":  "prop-200k-t1-r2-2025-11-07-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-07",
        "date":  "2025-11-07",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "DAILY",
        "inducement":  "NOT CONFIRMED",
        "pnl":  -100,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I did not feel any pressure or any emotional outburst, i was calm during the trade considering a possibility of me recovering the loss",
        "improve_win":  "",
        "improve_loss":  "Market looked like it took inducement and also looked like it did not, up till now i don\u0027t know for sure if it did or not but too avoid unnecessary loss i must avoid trading at all cost when there\u0027s indecisiveness",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r3-2025-11-12-eurjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-12",
        "date":  "2025-11-12",
        "pair":  "EURJPY",
        "htf_bias":  "BULLISH",
        "poi":  "DAILY",
        "inducement":  "CONFIRMED",
        "pnl":  800,
        "rr":  "",
        "risk":  null,
        "result":  "win",
        "notes":  "",
        "emotions":  "At first i was calm and not pressured but as the trade get closer too my tp i was in a little panic considering the possibility of it reversing and closed it before it hits tp",
        "improve_win":  "Next time I patiently wait for market too hit my tp cause I have my tp for a reason I did not randomly set it",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r4-2025-11-14-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-14",
        "date":  "2025-11-14",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  -160,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I was a bit excited which lead me too over refinement and then hitting stop loss, I was pressured during the trade but did not take any impulsive move but after the trade I was calm I felt so pained after hitting sl but I later calm down",
        "improve_win":  "",
        "improve_loss":  "I did over refinement which end leading too loss so I am going too add a clear rule in my strategy to avoid over refinement I hit SL because of failed reaction",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r5-2025-11-14-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-14",
        "date":  "2025-11-14",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  -170,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I was a bit excited which lead me too over refinement and then hitting stop loss, I was pressured during the trade but did not take any impulsive move but after the trade I was calm I felt so pained after hitting sl but I later calm down",
        "improve_win":  "",
        "improve_loss":  "I did over refinement which end leading too loss so I am going too add a clear rule in my strategy to avoid over refinement I hit SL because of failed reaction",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r6-2025-11-14-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-14",
        "date":  "2025-11-14",
        "pair":  "GBPUSD",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -170,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I took an unnecessary trade out of emotional outburst leading too me hitting stop loss",
        "improve_win":  "",
        "improve_loss":  "Next time I will stick too my rules thoroughly, all I need is extreme discipline",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r7-2025-11-18-usdcad",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-18",
        "date":  "2025-11-18",
        "pair":  "USDCAD",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  0,
        "rr":  "",
        "risk":  null,
        "result":  "be",
        "notes":  "",
        "emotions":  "I executed seemlessly, no emotional pressure on me",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r8-2025-11-20-usdcad",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-20",
        "date":  "2025-11-20",
        "pair":  "USDCAD",
        "htf_bias":  "BULLISH",
        "poi":  "DAILY",
        "inducement":  "CONFIRMED",
        "pnl":  -100,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I execute seemlessly, no emotional pressure but I wasn\u0027t able too take the decision of setting my trade on BE too aviod loss cause of extreme exhaustion I still executed, there was a little emotional pressure on me",
        "improve_win":  "",
        "improve_loss":  "I have too improve my discipline soo I will be able too take any logical decision properly at any situation During news event I have too make my stopp loss a little wider cause of the volatility",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r9-2025-11-20-usdcad",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-20",
        "date":  "2025-11-20",
        "pair":  "USDCAD",
        "htf_bias":  "BULLISH",
        "poi":  "DAILY",
        "inducement":  "CONFIRMED",
        "pnl":  -100,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I execute seemlessly, no emotional pressure but I wasn\u0027t able too take the decision of setting my trade on BE too aviod loss cause of extreme exhaustion I still executed, there was a little emotional pressure on me",
        "improve_win":  "",
        "improve_loss":  "I have too improve my discipline soo I will be able too take any logical decision properly at any situation During news event I have too make my stopp loss a little wider cause of the volatility",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r10-2025-11-21-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-21",
        "date":  "2025-11-21",
        "pair":  "GBPUSD",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -100,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I was pained cause my loss was as a reuslt of news manipulation",
        "improve_win":  "",
        "improve_loss":  "I should improve my strategy in terms of technical analysis too account for news manipulation and also learn fundamentals analysis",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r11-2025-11-21-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-21",
        "date":  "2025-11-21",
        "pair":  "GBPUSD",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -100,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I was pained cause my loss was as a reuslt of news manipulation",
        "improve_win":  "",
        "improve_loss":  "I should improve my strategy in terms of technical analysis too account for news manipulation and also learn fundamentals analysis",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r12-2025-11-21-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-21",
        "date":  "2025-11-21",
        "pair":  "GBPUSD",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  300,
        "rr":  "",
        "risk":  null,
        "result":  "win",
        "notes":  "",
        "emotions":  "I was pained cause my loss was as a reuslt of news manipulation",
        "improve_win":  "",
        "improve_loss":  "I should improve my strategy in terms of technical analysis too account for news manipulation and also learn fundamentals analysis",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r13-2025-11-24-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-24",
        "date":  "2025-11-24",
        "pair":  "GBPUSD",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -100,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "There wasn\u0027t any emotional pressure though my discipline was not firm that was the cause of my loss )",
        "improve_win":  "",
        "improve_loss":  "My loss was as a result of over refinement, I disrespected that rule with lead me too a loss , so I have too be more discipline",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r14-2025-11-26-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-26",
        "date":  "2025-11-26",
        "pair":  "GBPUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  300,
        "rr":  "",
        "risk":  null,
        "result":  "win",
        "notes":  "",
        "emotions":  "I was calm and not pressured and I executed well",
        "improve_win":  "I will try my best too execute my strategy perfectly well like I did in GBPUSD",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r15-2025-11-27-usdcad",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-27",
        "date":  "2025-11-27",
        "pair":  "USDCAD",
        "htf_bias":  "BULLISH",
        "poi":  "DAILY",
        "inducement":  "CONFIRMED",
        "pnl":  -100,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I executed my strategy calmly with no emotional pressure",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r16-2025-11-28-vol-10",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-28",
        "date":  "2025-11-28",
        "pair":  "VOL 10",
        "htf_bias":  "BEARISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  -100,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I felt pained actually cause I wasn\u0027t expecting market too go straight too my SL",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r17-2025-11-28-usdcad",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-28",
        "date":  "2025-11-28",
        "pair":  "USDCAD",
        "htf_bias":  "BULLISH",
        "poi":  "DAILY",
        "inducement":  "CONFIRMED",
        "pnl":  -100,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I executed my strategy seemlessly",
        "improve_win":  "",
        "improve_loss":  "I need too add some modification too my strategy, this loss was as a result of a break of rule from my last strategy which I did not add too the current one",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r18-2025-11-28-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-28",
        "date":  "2025-11-28",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -70,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "I hit sl because of failed reaction",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r19-2025-11-30-vol-25",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-30",
        "date":  "2025-11-30",
        "pair":  "VOL 25",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -50,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t1-r20-2025-11-30-vol-25",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-11-30",
        "date":  "2025-11-30",
        "pair":  "VOL 25",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -50,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t2-r2-2025-12-02-eurusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-12-02",
        "date":  "2025-12-02",
        "pair":  "EURUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -215,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I did not feel pressured, I was calm followed my rules and executed precisely",
        "improve_win":  "",
        "improve_loss":  "I Lost cause of how volatile the market was, honestly I executed my strategy down too the last rule and still lost",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t2-r3-2025-12-05-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-12-05",
        "date":  "2025-12-05",
        "pair":  "XAUUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -25,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I felt pained cause I executed my strategy down to the last rule and still lost, sha losses are part of the game",
        "improve_win":  "",
        "improve_loss":  "I executed my strategy down to the last rule and still lost, my loss was as a result of mis reading the charts",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t2-r4-2025-12-09-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-12-09",
        "date":  "2025-12-09",
        "pair":  "XAUUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -25,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I felt pained cause I executed my strategy down to the last rule and still lost",
        "improve_win":  "",
        "improve_loss":  "The loss I took was as a result of double inducement, my counter measures are to anticipate such possibilities",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t2-r5-2025-12-09-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-12-09",
        "date":  "2025-12-09",
        "pair":  "XAUUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -25,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I felt pained cause I executed my strategy down to the last rule and still lost",
        "improve_win":  "",
        "improve_loss":  "The loss I took was as a result of double inducement, my counter measures are to anticipate such possibilities",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t2-r6-2025-12-11-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-12-11",
        "date":  "2025-12-11",
        "pair":  "XAUUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  125,
        "rr":  "",
        "risk":  null,
        "result":  "win",
        "notes":  "",
        "emotions":  "I executed my strategy no emotional attachement",
        "improve_win":  "I executed my strategy perfectly well but anticipating double inducement this time, an improvement to add to my strategy is smt divergence an extra confirmation to confirm possibility of double inducement or not",
        "improve_loss":  "I executed my strategy as it is, no any emotional attachment",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t2-r7-2025-12-22-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-12-22",
        "date":  "2025-12-22",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  160,
        "rr":  "",
        "risk":  null,
        "result":  "win",
        "notes":  "",
        "emotions":  "No emotional attachement, executed my strategy as it is NO emotional pressure, though when market was close to my sl i was feeling a little pressure but I remind myself to be confident on my strategy and everything was clear",
        "improve_win":  "I notice that during the failed reaction on internal structure it is safer to stay outside the internal structure zone with ur sl",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t2-r8-2025-12-22-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-12-22",
        "date":  "2025-12-22",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  103,
        "rr":  "",
        "risk":  null,
        "result":  "win",
        "notes":  "",
        "emotions":  "No emotional attachement, executed my strategy as it is NO emotional pressure, though when market was close to my sl i was feeling a little pressure but I remind myself to be confident on my strategy and everything was clear",
        "improve_win":  "I notice that during the failed reaction on internal structure it is safer to stay outside the internal structure zone with ur sl",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t2-r9-2025-12-26-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-12-26",
        "date":  "2025-12-26",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -30,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "No emotional pressure, my strategy was executed perfectly well",
        "improve_win":  "",
        "improve_loss":  "I just need to widen my sl, even when consedring the possibility of deep retracement and kept my sl on the safe side market still wick me out, so my objective is to consider using more widen sl to avoid uinnesscary wick out",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t2-r10-2025-12-30-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2025-12-30",
        "date":  "2025-12-30",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -25,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "No emotional attachment",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r2-2026-01-05-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-05",
        "date":  "2026-01-05",
        "pair":  "GBPUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -25,
        "rr":  "1:5",
        "risk":  25,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I did not feel anything just executed my strategy as usual",
        "improve_win":  "",
        "improve_loss":  "My loss was a result of structural difference between the pairs, when such matter occur I will use the structure on my prop or broker to trade",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r3-2026-01-06-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-06",
        "date":  "2026-01-06",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -25,
        "rr":  "1:5",
        "risk":  25,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r4-2026-01-06-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-06",
        "date":  "2026-01-06",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  -25,
        "rr":  "1:6",
        "risk":  25,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r5-2026-01-09-vol25",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-09",
        "date":  "2026-01-09",
        "pair":  "VOL25",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -25,
        "rr":  "1:5",
        "risk":  25,
        "result":  "loss",
        "notes":  "",
        "emotions":  "No emotional outburst, executed my strategy as it is",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r6-2026-01-14-eurusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-14",
        "date":  "2026-01-14",
        "pair":  "EURUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -44,
        "rr":  "1:22",
        "risk":  39,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I did not actaully feel any emotional pressure cause I understood the reason for my lose",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r7-2026-01-21-eurjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-21",
        "date":  "2026-01-21",
        "pair":  "EURJPY",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  0,
        "rr":  "1:15",
        "risk":  25,
        "result":  "be",
        "notes":  "",
        "emotions":  "I felt pained actually, emotional spike and all that but was as a result of external factors",
        "improve_win":  "",
        "improve_loss":  "The only pluasible explanation for my loss is double inducement, even using smt divergence to cancel the possibility of double idm it is still very much possible",
        "improve_be":  "I just need to make my rules more fexible to aviod market hitting my be and going to my tp and also protect capital",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r8-2026-01-21-eurjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-21",
        "date":  "2026-01-21",
        "pair":  "EURJPY",
        "htf_bias":  "BULLUSH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  19,
        "rr":  "1:5",
        "risk":  null,
        "result":  "win",
        "notes":  "",
        "emotions":  "I felt pained actually, emotional spike and all that but was as a result of external factors",
        "improve_win":  "",
        "improve_loss":  "The only pluasible explanation for my loss is double inducement, even using smt divergence to cancel the possibility of double idm it is still very much possible",
        "improve_be":  "I just need to make my rules more fexible to aviod market hitting my be and going to my tp and also protect capital",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r9-2026-01-21-eurjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-21",
        "date":  "2026-01-21",
        "pair":  "EURJPY",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  -25,
        "rr":  "1:5",
        "risk":  25,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I felt pained actually, emotional spike and all that but was as a result of external factors",
        "improve_win":  "",
        "improve_loss":  "The only pluasible explanation for my loss is double inducement, even using smt divergence to cancel the possibility of double idm it is still very much possible",
        "improve_be":  "I just need to make my rules more fexible to aviod market hitting my be and going to my tp and also protect capital",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r10-2026-01-23-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-23",
        "date":  "2026-01-23",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "",
        "pnl":  -50,
        "rr":  "",
        "risk":  null,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "My loss on this was invalid, I left me limit which was already invalid and market executed it during the night and took me out on extra losses cause of slippage",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r11-2026-01-27-eurjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-27",
        "date":  "2026-01-27",
        "pair":  "EURJPY",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  145,
        "rr":  "1:5",
        "risk":  25,
        "result":  "win",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "I will say I executed pretty well, I should try replicating same act over all trades",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r12-2026-01-22-eurusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-22",
        "date":  "2026-01-22",
        "pair":  "EURUSD",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  0,
        "rr":  "1:5",
        "risk":  25,
        "result":  "be",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "The reason for break even was valid though I should looked for a second entry cause my setup was still valid",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t3-r13-2026-01-30-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-01-30",
        "date":  "2026-01-30",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  -66,
        "rr":  "1:5",
        "risk":  66,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t4-r2-2026-02-04-usdcad",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-02-04",
        "date":  "2026-02-04",
        "pair":  "USDCAD",
        "htf_bias":  "BEARISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:10",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I will say I wasn\u0027t up guard, some how cause of my recent wins I was relaxed",
        "improve_win":  "",
        "improve_loss":  "This loss was as a result of news, I did not check news before entering, market went for a second inducement, I need to be more discipline",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t4-r3-2026-02-04-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-02-04",
        "date":  "2026-02-04",
        "pair":  "XAUUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:10",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I will say I wasn\u0027t up guard, some how cause of my recent wins I was relaxed",
        "improve_win":  "",
        "improve_loss":  "This loss was as a result of structural misread , I need to work on understanding market structure more, to aviod problems like this",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t4-r4-2026-02-05-usdcad",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-02-05",
        "date":  "2026-02-05",
        "pair":  "USDCAD",
        "htf_bias":  "BEARISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:10",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "No emotional pressure or attachment",
        "improve_win":  "",
        "improve_loss":  "Base on my understanding of the market this loss was as a result of market changing trend, basically creating a structure on the higher time frame, my strategy has no account for such scenario so I have to look into this market behaviour and study it",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t4-r5-2026-02-03-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-02-03",
        "date":  "2026-02-03",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  2300,
        "rr":  "1:5",
        "risk":  1000,
        "result":  "win",
        "notes":  "",
        "emotions":  "No emotional pressure",
        "improve_win":  "",
        "improve_loss":  "Market hit my trailing sl, well there was a condition I used trailing sl to secure small profits instead of just staying on BE",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t4-r6-2026-02-03-eurusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-02-03",
        "date":  "2026-02-03",
        "pair":  "EURUSD",
        "htf_bias":  "BULLISH",
        "poi":  "1H",
        "inducement":  "CONFIRMED",
        "pnl":  5200,
        "rr":  "1:5",
        "risk":  1000,
        "result":  "win",
        "notes":  "",
        "emotions":  "No emotional pressure",
        "improve_win":  "My strategy was executed seamlessly and my goal is to able to do that consistently",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t4-r7-2026-02-05-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-02-05",
        "date":  "2026-02-05",
        "pair":  "XAUUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:10",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t4-r8-2026-02-05-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-02-05",
        "date":  "2026-02-05",
        "pair":  "XAUUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:10",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t4-r9-2026-02-09-eurjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-02-09",
        "date":  "2026-02-09",
        "pair":  "EURJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:5",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "During this ej loss I felt a bit because I thought I don\u0027t know the cause of the loss but now I feel relaxed, after finding out the cause of my losses",
        "improve_win":  "",
        "improve_loss":  "The cause of both losses was a deep retracement and failed reaction, the cause of both is most likely my structural reading, I need to work on it exetremly well",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t4-r10-2026-02-09-eurjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-02-09",
        "date":  "2026-02-09",
        "pair":  "EURJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:5",
        "risk":  1500,
        "result":  "loss",
        "notes":  "",
        "emotions":  "During this ej loss I felt a bit because I thought I don\u0027t know the cause of the loss but now I feel relaxed, after finding out the cause of my losses",
        "improve_win":  "",
        "improve_loss":  "The cause of both losses was a deep retracement and failed reaction, the cause of both is most likely my structural reading, I need to work on it exetremly well",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t5-r15-2026-03-25-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-03-25",
        "date":  "2026-03-25",
        "pair":  "XAUUSD",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -500,
        "rr":  "1:6",
        "risk":  500,
        "result":  "loss",
        "notes":  "",
        "emotions":  "No emotional pressure",
        "improve_win":  "",
        "improve_loss":  "Change in market trend/Failed reaction",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t5-r16-2026-03-25-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-03-25",
        "date":  "2026-03-25",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -500,
        "rr":  "1:5",
        "risk":  500,
        "result":  "loss",
        "notes":  "",
        "emotions":  "No emotional presssure or any sign of emotion No emotional pressure",
        "improve_win":  "",
        "improve_loss":  "Double inducement Deep retracement",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t5-r17-2026-03-25-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-03-25",
        "date":  "2026-03-25",
        "pair":  "USDJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -500,
        "rr":  "1:5",
        "risk":  500,
        "result":  "loss",
        "notes":  "",
        "emotions":  "No emotional presssure or any sign of emotion No emotional pressure",
        "improve_win":  "",
        "improve_loss":  "Double inducement Deep retracement",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t5-r18-2026-03-27-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-03-27",
        "date":  "2026-03-27",
        "pair":  "XAUUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -500,
        "rr":  "1:5",
        "risk":  500,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t5-r19-2026-03-27-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-03-27",
        "date":  "2026-03-27",
        "pair":  "GBPUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -500,
        "rr":  "1:5",
        "risk":  500,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t5-r20-2026-03-27-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-03-27",
        "date":  "2026-03-27",
        "pair":  "XAUUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  5000,
        "rr":  "1:10",
        "risk":  500,
        "result":  "win",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t6-r2-2026-04-02-eurusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-04-02",
        "date":  "2026-04-02",
        "pair":  "EURUSD",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -500,
        "rr":  "1:10",
        "risk":  500,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I will say i have been stable emotions, no impulse move taken in a long time",
        "improve_win":  "",
        "improve_loss":  "Result of losses was as a result of double idm, which I\u0027m curently working on solving that issue",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t6-r3-2026-04-03-eurusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-04-03",
        "date":  "2026-04-03",
        "pair":  "EURUSD",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -500,
        "rr":  "1:5",
        "risk":  500,
        "result":  "loss",
        "notes":  "",
        "emotions":  "No emotional pressure",
        "improve_win":  "",
        "improve_loss":  "Result of losses was as a result of double idm, which I\u0027m curently working on solving that issue",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t6-r4-2026-04-03-eurusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-04-03",
        "date":  "2026-04-03",
        "pair":  "EURUSD",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  0,
        "rr":  "1:5",
        "risk":  500,
        "result":  "be",
        "notes":  "",
        "emotions":  "No emotional pressure",
        "improve_win":  "",
        "improve_loss":  "Result of losses was as a result of double idm, which I\u0027m curently working on solving that issue",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t6-r5-2026-04-06-eurjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-04-06",
        "date":  "2026-04-06",
        "pair":  "EURJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  2500,
        "rr":  "1:5",
        "risk":  500,
        "result":  "win",
        "notes":  "",
        "emotions":  "No emotional pressure",
        "improve_win":  "I need to execute my strategy as it again, just like I did and won the trade",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t6-r6-2026-04-17-eurusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-04-17",
        "date":  "2026-04-17",
        "pair":  "EURUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:5",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t6-r7-2026-04-20-usdjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-04-20",
        "date":  "2026-04-20",
        "pair":  "USDJPY",
        "htf_bias":  "BEARISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:5",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I want to trade against bais as a result of fustration on slow progress",
        "improve_win":  "",
        "improve_loss":  "My loss was as a result of trading against bais",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t6-r8-2026-04-23-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-04-23",
        "date":  "2026-04-23",
        "pair":  "GBPUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "",
        "pnl":  -1000,
        "rr":  "1:5",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "All my conflueces in my strategy was not tick but I went ahead to take the trade because of fustration of slow progress but I will correct that",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t6-r9-2026-04-23-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-04-23",
        "date":  "2026-04-23",
        "pair":  "GBPUSD",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:5",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "All my conflueces in my strategy was not tick but I went ahead to take the trade because of fustration of slow progress but I will correct that",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t6-r10-2026-04-28-eurjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-04-28",
        "date":  "2026-04-28",
        "pair":  "EURJPY",
        "htf_bias":  "BULLISH",
        "poi":  "",
        "inducement":  "",
        "pnl":  -1000,
        "rr":  "",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "",
        "improve_win":  "",
        "improve_loss":  "",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t7-r2-2026-05-14-gbpusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-05-14",
        "date":  "2026-05-14",
        "pair":  "GBPUSD",
        "htf_bias":  "BULLISH",
        "poi":  "D",
        "inducement":  "CONFIRMED",
        "pnl":  -500,
        "rr":  "1:8",
        "risk":  500,
        "result":  "loss",
        "notes":  "",
        "emotions":  "There was not any form or sign of emotion, I accepted the loss and moved on",
        "improve_win":  "",
        "improve_loss":  "My losses was a result of a deeper retracement which I already anticipated, so I risked little on that",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t7-r3-2026-05-19-gbpjpy",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-05-19",
        "date":  "2026-05-19",
        "pair":  "GBPJPY",
        "htf_bias":  "BULLISH",
        "poi":  "4H",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:8",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "There was not any form or sign of emotion, I accepted the loss and moved on",
        "improve_win":  "",
        "improve_loss":  "I lost this trade because of a double inducement",
        "improve_be":  "",
        "sync_status":  "imported"
    },
    {
        "import_id":  "prop-200k-t7-r4-2026-05-29-xauusd",
        "source":  "TRADE JOURNAL(PROP FIRM) 200K.docx",
        "created_at":  "2026-05-29",
        "date":  "2026-05-29",
        "pair":  "XAUUSD",
        "htf_bias":  "BEARISH",
        "poi":  "D",
        "inducement":  "CONFIRMED",
        "pnl":  -1000,
        "rr":  "1:10",
        "risk":  1000,
        "result":  "loss",
        "notes":  "",
        "emotions":  "I was actually fustrated on this because I did not see any take profit that month and last",
        "improve_win":  "",
        "improve_loss":  "I lost this trade as a result of a structural mis read",
        "improve_be":  "",
        "sync_status":  "imported"
    }
];
